### ISSUE TITLE
Adamantium Pick bug

### ISSUE THREAD

**Issue by DanShu15** [i509VCB/CursedShulkerBoxes#11]
I had a server member submit their player log and report that after using an adamantium pick to grab their bulky shulky it's contents had been wiped. I reported the issue with logs at https://github.com/Brandcraf06/AdabraniumMod/issues/5 but I'm not certain which mod had the problem, so I'm cross-posting the issue here as well :)

**Comment by DanShu15** [comment]
Thanks for your help on that :)
As mentioned over on Adabranium it does appear the pick used had veining III on it so the NBT data wasn't kept after it was broken

**Comment by i509VCB** [comment]
Make sure you file the bug report on diggus maximus so this doesn't occur in the future

**Comment by DanShu15** [comment]
ok I'll crosspost to them and to the mo enchantments which adds the veining enchantment
Reported it to Mo Enchantments, apparently it was resolved in a previous fix with Diggus https://github.com/kyrptonaught/DiggusMaximus/issues/5
