### ISSUE TITLE
Cannot craft copper or platium varients in 1.0.4

### ISSUE THREAD

**Issue by Cheeseborgers** [i509VCB/CursedShulkerBoxes#5]
I'm currently running:

- BulkyShulkies 1.0.4
- Minecraft 1.15.2
- TechReborn-1.15-3.3.3+build.182

And here is the server config.json (omitting comments).

magnetismTickDelay=20
notAllowedInShulkers=null
platinumMagnetMaxRange=6
schemaVersion=1
shouldPlatinumUseMagnetism=true
useResources=true

**Comment by i509VCB** [comment]
Sorry for being a bit slow on the response, could you load up a singleplayer world with that environment and give me the full log?

**Comment by Cheeseborgers** [comment]
Apologies myself for the late response. heres a log from a completely new minecraft 1.15.2 instance and single player world.
[latest.log](https://github.com/i509VCB/BulkyShulkies/files/4244000/latest.log)

**Comment by Cheeseborgers** [comment]
Apologises myself for the late reply. hears is a log from a single player world on a completely new fabric mc instance.

[https://github.com/Cheeseborgers/log_dumps/blob/master/latest.log](url)

**Comment by i509VCB** [comment]
Parsing error loading recipe ml:grass_layer

convth:seed_diamond

convth:seed_coal

convth:seed_diamond

convth:seed_emerald

convth:seed_coal

Bulky shulkies has no errors with recipes but other mods have recipe issues. Go give those mods a look. Another test would be is run TechReborn and bulky shulkies in isolation to verify my recipes are functioning properly

**Comment by Cheeseborgers** [comment]
I've replicated it in a fresh fabric instance in a separate directory to my usual launcher setup. with - fabric loader 0.7.8+build.184 and MC 1.15.2

 Using only the following mods:

- bulkyshulkies-1.0.4.jar
- fabric-api-0.4.32+build.292-1.15.jar
- RebornCore-1.15-4.2.3+build.99.jar
- RoughlyEnoughItems-3.5.4.jar
- TechReborn-1.15-3.3.4+build.189.jar

These two lines stick out to me if they mean anything.

`[10:36:26] [REI-SyncRecipes/INFO]: [REI] Loading 4 plugins: bulkyshulkies:reiplugin, roughlyenoughitems:default_auto_crafting_plugin, techreborn:techreborn_plugin, roughlyenoughitems:default_plugin

[10:36:26] [REI-SyncRecipes/WARN]: [REI] Someone is registering exclusion zones with the deprecated method: me.i509.fabric.bulkyshulkies.client.BulkyShulkiesREIPlugin$$Lambda$4215/1669656581`

[https://github.com/Cheeseborgers/log_dumps/blob/master/shulkers.log](url)

**Comment by i509VCB** [comment]
The second message is an REI thing related to the screen. I will fix that but it's unrelated to the issue at hand. I'll look at the log of course.

**Comment by i509VCB** [comment]
Also the log you attached is inaccessible. Could you link another one?
