### ISSUE TITLE
[Suggestion/Compatibility] "Backpack style" Box or Quick Shulker compatibility 

### ISSUE THREAD

**Issue by homemmakako** [i509VCB/CursedShulkerBoxes#6]
Is it possible to make it so upgraded shulker boxes open when right-clicked, like a backpack would (maybe only available on a certain tier) ?  I feel like this should be possible even in vanilla :stuck_out_tongue_closed_eyes:

Another suggestion/option would be to make the upgraded shulker boxes compatible with the [Quick Shulker](https://www.curseforge.com/minecraft/mc-mods/quick-shulker) mod.

**Comment by i509VCB** [comment]
I was actually planning on adding a shulker box helmet that acts like a wearable shulker box complete with lid animation (You can view the starts of it in the 1.16.x branch).

Looking at the code for Quick Shulker, there isn't going to be any easy way to add my own hooks into it without having to overwrite half of his code. 

Edit:
I am probably going to work on the functional aspects of the helmet tomorrow, the rendering magic is going to take a bit longer.

**Comment by i509VCB** [comment]
The author of Quick Shulker has contacted me and is working on his own implementation into quick shulker.

**Comment by i509VCB** [comment]
Merged in https://github.com/i509VCB/BulkyShulkies/commit/fb74a4cbc89bc6237acff28e89794b9870c447bf
