### ISSUE TITLE
Incorrect translation on Magenta boxes being set as purple

### ISSUE THREAD

**Issue by i509VCB** [i509VCB/CursedShulkerBoxes#7]
Magenta boxes are incorrectly named as "Purple", will be fixed in a quick hotfix.

@HeresHavi I don't know dutch, could you get a firm translation of what "Magenta" is?

**Comment by HeresHavi** [comment]
> @HeresHavi I don't know dutch, could you get a firm translation of what "Magenta" is?

Magenta will be written the same as in English just pronounced differently

**Comment by i509VCB** [comment]
Alright I'll apply that change and force push

**Comment by i509VCB** [comment]
Closed and fixed https://github.com/i509VCB/BulkyShulkies/commit/63a0e59d0ebaaeac2c2977f4583d21b2c960c462
