### ISSUE TITLE
Platinium shulker box bug

### ISSUE THREAD

**Issue by FaultyPixel** [i509VCB/CursedShulkerBoxes#9]
While doing some testing i put a platinium shulker box on the ground and threw items on the ground to figure out the range but sometimes the items on the block directly on the side won't get picked up while an item thrown from 5-6 blocks away while be picked up before it even touches the ground. 
I just found out that actually, the shulker box will only pick items from the south-est corner as you can see on the following image : 
![2020-04-25_17 44 18](https://user-images.githubusercontent.com/64114112/80284083-834e4400-871c-11ea-91a5-ca6b03b11342.png)

**Comment by i509VCB** [comment]
Yeah this isn't right, I originally wanted to center the checks but I seem to have botched it. I'll fix it so it's centered on the box and document it a little better (maybe an item to show a bounding box around the range of the item pickup.

Items directly on the side not being picked up is a sort of issue with undocumented behavior, but I do want to make it pick up items directly to the side.

Maybe also fire an actual particle effect on the item so you can visibly see it was picked up rather than vanishing into a box.

**Comment by FaultyPixel** [comment]
Both the item to show the bounding box and the particule effect seems to be awesome ideas ! To avoid performance issue if a lot of items are constantly picked up maybe the particule effect could only be visible with the said item ? I don't know if it is doable or a even good suggestion actually ! Anyway, thank you, it is already an incredibly useful mod !

**Comment by i509VCB** [comment]
Yeah it would only be visible on the item being picked up when using the particles. I already allow the rate at which the magnet applies to be configured.

**Comment by i509VCB** [comment]
I'll work on those concepts above tomorrow or on the weekend.

**Comment by i509VCB** [comment]
So it was a bit more than a weekend, I've fixed the bug with the magnets and added a wand to show the box that corresponds to the magnetic region (texture pending). This box also changes with the configured magnetic range (I need to look into making the client use the server's config value for this).

![image](https://user-images.githubusercontent.com/30619168/84221703-781c6100-aa9b-11ea-9c7a-5798494e63af.png)

I also plan to add a configuration option to change the box color and another option to hide all other boxes when looking directly at one of the shulker boxes.

**Comment by i509VCB** [comment]
I am happy with the fix that is currently on 20w30a branch (added the feature where looking at a box only shows it's outline). I'll probably start releasing weekly builds on snapshots with these things and it will be in with 1.16.2 when it is released.
